# OTOMATIK ÜRETİLDİ - elle düzenlemeyin.
# Kaynak: /home/claude/sigma_work/source_rules/fortigate/fortinet_fortigate_new_admin_account_created.yml
# Üretici: convert_sigma_rules.py
id: cd0a4943-0edd-42cf-b50c-06f77a10d4c1
name: FortiGate - New Administrator Account Created
level: 8
size: '>0'
active: true
author:
- Marco Pedrinazzi (@pedrinazziM) (InTheCyber)
group: fortigate
tags:
- attack.persistence
- attack.t1136.001
description: Detects the creation of an administrator account on a Fortinet FortiGate
  Firewall.
sigma: false
data:
  source_sigma_id: cd0a4943-0edd-42cf-b50c-06f77a10d4c1
rule: |-
  {
    "query": {
      "bool": {
        "must": [
          {
            "query_string": {
              "query": "data.action:Add AND data.cfgpath:system.admin",
              "analyze_wildcard": true
            }
          }
        ],
        "filter": [
          {
            "range": {
              "@timestamp": {
                "gte": "{{ startime }}",
                "lte": "{{ endtime }}",
                "format": "epoch_second"
              }
            }
          }
        ]
      }
    }
  }
