define ROOT C:\Tools

Moduledir %ROOT%\modules
CacheDir   %ROOT%\data
Pidfile    %ROOT%\data\nxlog.pid
SpoolDir   %ROOT%\data
LogFile    %ROOT%\data\nxlog.log

<Extension json>
    Module xm_json
</Extension>

<Input sysmon_in>
    Module im_msvistalog
    Query <QueryList>\
            <Query Id="0">\
              <Select Path="Microsoft-Windows-Sysmon/Operational">*</Select>\
            </Query>\
          </QueryList>
    Exec if ($EventID == 13 and $Message =~ /InventoryApplicationFile|InvDB-/) drop();
</Input>

<Output wazuh_out>
    Module om_ssl
    Host WAZUH_MANAGER_IP
    Port 6514
    CAFile C:\Tools\wazuh-ca.pem
    AllowUntrusted TRUE
    Exec to_json();
</Output>

<Route sysmon_to_wazuh>
    Path sysmon_in => wazuh_out
</Route>
